name: Build and add the Util library to a release

on:
    release:
        types: [created]

jobs:
    build-and-package:
        runs-on: windows-latest # Needs windows to build .lib

        steps:
        -   name: Checkout code
            uses: actions/checkout@v3

        -   name: Build project
            run: scripts/build.bat
            shell: cmd

        -   name: Prepare release folder
            run: |
                mkdir package
                copy bin\PashaBibko-UTIL.lib package\PB-UTIL.lib
                scripts/prepare-headers.bat

        -   name: Create ZIP file
            run: powershell Compress-Archive -Path package\* -DestinationPath PB-UTIL.zip

        -   name: Upload ZIP to release
            uses: softprops/action-gh-release@v1
            with:
                files: PB-UTIL.zip
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
