name: Build and deploy doxygen documentation

on:
    push:
        branches:
            - docs # Dedicated branch for pushing to when ready for documentation

jobs:
    build-docs:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v3

        -   name: Install doxygen
            uses: sudo apt-get update && sudo apt-get install -y doxygen graphviz

        -   name: Generate documentation
            uses: doxygen Doxyfile

        -   name: Deploy to github pages
            uses: peaceiris/actions-gh-pages@v4
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./docs
